name: Build
on: ['push']
jobs:
  build:
    runs-on: ubuntu-latest
    container: gitlab-registry.cern.ch/muon-collider/mucoll-deploy/mucoll:2.9-alma9
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Build Source Code
        run: |
          source /opt/setup_mucoll.sh
          cmake -S. -Bbuild
          cmake --build build
